[project]
name = "agent-venv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ddgs>=9.0.0",
    "openai>=1.84.0",
    "requests>=2.32.3",
]
